### ISSUE TITLE
docker build -t "pctf-team" .

### ISSUE THREAD

**Issue by lushenle** [zjlywjh001/phrackCTF-Team-Docker#1]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   337  100   337    0     0    576      0 --:--:-- --:--:-- --:--:--   576

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c groupadd tomcat && 	useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && 	cd /tmp && 	curl -O http://mirrors.advancedhosters.com/apache/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz && 	mkdir /opt/tomcat && 	tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1 && 	cd /opt/tomcat && 	chgrp -R tomcat /opt/tomcat && 	chmod -R g+r conf && 	chmod g+x conf && 	chown -R tomcat webapps/ work/ temp/ logs/' returned a non-zero code: 2

**Comment by zjlywjh001** [comment]
fixed on aaf18090b05114f609729177c7b2b5d6a2ef0ce9
